spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: cqptogojihajfs
    password: 98196c56354d7f6387e97b09afe617f5918678e428e6c4077effb059d686c941
    url: postgres://cqptogojihajfs:98196c56354d7f6387e97b09afe617f5918678e428e6c4077effb059d686c941@ec2-63-34-223-144.eu-west-1.compute.amazonaws.com:5432/dais9trjd8i6nk
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialec
    database: postgresql

server:
   port: 8081