spring:
  datasource:
    driver-class-name: 
    username: 
    password: 
    url: 
    platform: 
    initialization-mode: 
    continue-on-error: 
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialec
    database: postgresql

server:
   port: 8081